### ISSUE TITLE
Snapshot size is too small

### ISSUE THREAD

**Issue by pikeupe** [laurentalacoque/TouchSelfie#30]
___Translated___
Hello

  I hope I'm asking in the right place, how can I obtain photos of greater size on the USB stick, because currently the photos on the USB do not exceed 250 KB

as I'm a beginner, not obvious. Thank you for this work

___Original Message___

> Bonjour
> 
>  J’espère demander au bon endroit, comment peut-on faire pour avoir les photos de meilleurs taille sur le support USB car actuellement les photos sur l'USB ne dépassassent pas 250 ko
> 
> comme je débute pas évident merci pour ce travail

**Comment by laurentalacoque** [comment]
Hello @pikeupe,
Sorry for my translation, english is preferred for international collaboration ;)

## Short answer
Tune the `snap_size` property of the `EFFECT_PARAMETERS` dict in file `scripts/constants.py` to enhance snaphot resolution. (You will still be limited to your camera hardware)

## Longer answer
Picture sizes depends on: 
- Snapshot resolution (and utlimately camera resolution)
- Image content
- JPEG compression

Using PiCamera, you can only act on snapshot resolution.
I chose to keep resolution low (although higher than original TouchSelfie) in order to obtain lightweight yet readable snapshots.

Typically, the settings in `constants.py` are tuned to the quarter of picamera v2.1 full resolution.
You can change the `snap_size` values up-to the full camera resolution (which is (3280,2464) for the official v2.1 camera module)

**Comment by laurentalacoque** [comment]
# How to solve

- Change `snap_size` properties in `EFFECT_PARAMETERS` dict of `constants.py`

- Potential enhancement: add a quality/size configuration option
  - [ ] Detect camera max resolution
  - [ ] Ask for user's preferences in the setup step
  - [ ] Ajust "snap_size" properties accordingly

**Comment by pikeupe** [comment]
Hello

thank you for your explanation and this work
