### ISSUE TITLE
Hardware Buttons

### ISSUE THREAD

**Issue by jdb1982** [laurentalacoque/TouchSelfie#75]
Hello, 

I have just setup our TouchSelfie and everything works except the hardware buttons. I have the button attached to GPIO 8(physical pin 24) and GND. When I press the button it will not start the count down. Using a python script so I know the button is functioning because I can get a response after pressing.

**Comment by laurentalacoque** [comment]
Hello @jdb1982 !
Currently, because hardware buttons depend on your particular hardware, you must edit the code to enable them.

See [this block](https://github.com/laurentalacoque/TouchSelfie-extended/blob/ce29c19322561e1116a0d418f9fe04a569e5e893/scripts/constants.py#L165) in the `scripts/constants.py` to configure your GPIO pins and pull-up / pull-down states.

Also, once you've run the setup script, open the `scripts/configuration.json` file in a file editor and change the `enable_hardware_buttons` to `true`.
Then it should work !

Closing the issue, feel free to reopen ;)
