### ISSUE TITLE
Picture are pink

### ISSUE THREAD

**Issue by karlzre** [laurentalacoque/TouchSelfie#78]
Hi Laurent,

I see that most of the pictures are pink.

Any idee of it s a setup somewhere on the camera or is it from the environement ? 

https://photos.app.goo.gl/VTchW9YuDsuNfSJc8

I m using a neopixel band as flash i havn t enough power then the lights is a litle bit green, this may be the cause ? 

Thx

**Comment by laurentalacoque** [comment]
Hey @karlzre 
This certainly is due to a poor white balance (caused by the camera settings / light source)
Note that this isn't related to touchselfie which doesn't alter the camera parameters regarding white balance.

I think that the greenish light can certainly cause the issue, as the white balance will be automatically done by the camera so that the green light appears white (and hence will boost the opposite color)
